import { Weight } from "lucide-react";
import image1 from "../../public/assets/product/product1.jpg";
import image2 from "../../public/assets/product/product2.jpg";
import image3 from "../../public/assets/product/product3.jpeg";
import image4 from "../../public/assets/product/product4.webp";
import image5 from "../../public/assets/product/product5.webp";
import image6 from "../../public/assets/product/product6.webp";
import image7 from "../../public/assets/product/product7.jpeg";
import image8 from "../../public/assets/product/product8.jpeg";
export const product = [
  {
    id: 1,
    category: "Hair Treatment",
    title: "RedOne Matte Hair Wax",
    price: "65,000",
    image: image1,
    brand: "RedOne",
    Weight: "0.45kg",
  },
  {
    id: 2,
    category: "Hair Treatment",
    title: "RedOne Aqua Hair Wax Full Force",
    price: "65,000",
    image: image2,
    brand: "RedOne",
    Weight: "0.45kg",
  },
  {
    id: 3,
    category: "Hair Treatment",
    title: "Mielle Rosemary Scalp&Hair Strengthening Oil",
    price: "125,000",
    image: image3,
    brand: "RedOne",
    Weight: "0.45kg",
  },
  {
    id: 4,
    category: "Conditioner, Hair Treatment",
    title: "Mielle Rosemary Mint Daily Styling Creme",
    price: "155,000",
    image: image4,
    brand: "RedOne",
    Weight: "0.45kg",
  },
  {
    id: 5,
    category: "Conditioner, Hair Treatment",
    title: "Mielle Rosemary Mint Strengthening Leave-In Conditioner",
    price: "155,000",
    image: image5,
    brand: "RedOne",
    Weight: "0.45kg",
  },
  {
    id: 6,
    category: " Hair Treatment",
    title: "Mielle Rosemary Mint Strengthening Hair Masque",
    price: "155,000",
    image: image6,
    brand: "RedOne",
    Weight: "0.45kg",
  },
  {
    id: 7,
    category: " Hair Treatment",
    title: "Mielle Rosemary Mint Strengthening Conditioner",
    price: "155,000",
    image: image7,
    brand: "RedOne",
    Weight: "0.45kg",
  },
  {
    id: 8,
    category: "Conditioner, Hair Treatment",
    title: "Mielle Pomegranate & Honey Leave-In Conditioner",
    price: "150,000",
    image: image8,
    brand: "RedOne",
    Weight: "0.45kg",
  },
];

export const productCatogories = [
  "Afrokinky",
  "Bar Soap",
  "Body Cream & Lotion",
  "Body Lotion",
  "Braids",
  "Brush",
  "Canned Food",
  "Cereal & Milk",
  "Cloths",
  "Comb",
  "Conditioner",
  "Crochet",
  "Detangler",
  "Facial Treatment",
  "Flours & Meals",
  "Food",
  "Hair Cap",
  "Hair Cream",
  "Hair Extension",
  "Hair Glue & Clips",
  "Hair Ribbon",
  "Hair Treatment",
  "Human Hair",
  "Jewelry",
  "Kid Relaxer",
  "Kid Shampoo",
  "Make-Up Kits",
  "Musical Instrument",
  "Oil",
  "Oil & Sauce",
  "On Sale",
  "Parfume",
  "Pony Tail",
  "Relaxer",
  "Shoes",
  "Shower Gel",
  "Snacks",
  "Soup Ingredients",
  "Spices",
  "Sulphate Free Product",
  "Weave-On",
  "Wig",
  "Wig Cap",
];
