import type { Metadata } from "next";
import { Prociono } from "next/font/google";
import "./globals.css";
import Providers from "@/lib/Provider";

// Import Prociono font
const prociono = Prociono({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Afro beauty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={prociono.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
